# This has been created by @lillieH1000

name: Build the YouTube Reborn deb

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Cache Submodules
        id: cache-submodule
        uses: actions/cache@v3
        with:
          path: |
            theos
            YouTubeHeader
          key: ${{ runner.os }}-submodules
          
      - name: Update git submodules
        if: steps.cache-submodule.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache chrisharper22/sdks
        id: cache-sdks
        uses: actions/cache@v3
        with:
          path: |
            theos/sdks
          key: ${{ runner.os }}-sdks

      - name: Update chrisharper22/sdks
        if: steps.cache-sdks.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: chrisharper22/sdks
          ref: main
          sparse-checkout: iPhoneOS16.2.sdk
          path: theos/sdks

      - name: Build Package 
        run: |
          brew install make xz ldid 
          export THEOS=theos
          gmake clean package FINALPACKAGE=1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
