# This has been created by @lillieH1000

name: Build the YouTube Reborn deb

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout @main
        uses: actions/checkout@main

      - name: Update git submodules
        if: steps.cache-test-fixture.outputs.cache-hit != 'true'
        run:
          git submodule update --init --recursive

      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.0
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Checkout chrisharper22/sdks
        if: steps.SDK.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: chrisharper22/sdks
          ref: main
          sparse-checkout: iPhoneOS16.2.sdk
          path: theos/sdks

      - name: Build Package 
        run: |
          brew install make xz ldid 
          export THEOS=theos
          gmake clean package FINALPACKAGE=1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: packages/*.deb
